### ISSUE TITLE
Request: Maestro Mode keyboard control

### ISSUE THREAD

**Issue by mighele** [Eusth/Illusion-Plugins#2]
Hi Eusth.

Would it be possible for Maestro Mode to work completely from the keyboard? It is unusable with the mouse when using the Rift. Having it work on keyboard would be great.

Thanks
Mike

**Comment by Eusth** [comment]
Heyho mighele

Well, it would be possible, sure, but what kind of control do you have in mind? Something along the lines of selecting a handle via tab and moving it blender-like via some key combination / arrow keys?

I may get back to it when I have time, but for now I'd say we wait for the studio and build up on that.

As a side-note, I implemented an experimental cursor for the rift that works better with IK nodes for the studio in Harem Mate. Might also be an option to port that over.

[edit] Only noticed your PR now. Taking a look at it. Thanks a bunch! ;)
