### ISSUE TITLE
IEnhancedPlugin#Filter doesn't work correctly for Download version of the PlayClub / PlayClubStudio.

### ISSUE THREAD

**Issue by vrvrl0ver** [Eusth/Illusion-Plugins#6]
Download version of the PlayClub and PlayClubStudio runs "PlayClub.bin" instead of "PlayClub.exe".
For this case, System.Diagnostics.Process.GetCurrentProcess().ProcessName returns "PlayClub.bin" instead of the "PlayClub" that supposed to be returned for the PlayClub.exe.

Here is the quick hack on IllusionInjector.dll, which to be working with both normal version and DL version.

namespace IllusionInjector
{
    static class PluginManager
    {

```
    public static IEnumerable<IPlugin> LoadPlugins()
    {
        string pluginDirectory = Path.Combine(Environment.CurrentDirectory, "Plugins");
        string exeName = (System.Diagnostics.Process.GetCurrentProcess().ProcessName);

        if (exeName.EndsWith(".bin"))
        {
            //For DL version
            exeName = exeName.Substring(0, exeName.Length - 4);// Just remove .bin
        }
```

**Comment by Eusth** [comment]
Can you try if this version works with the DL edition?

[IllusionInjector.zip](https://github.com/Eusth/Illusion-Plugins/files/307607/IllusionInjector.zip)

**Comment by vrvrl0ver** [comment]
Thank you so mush , and sorry for delayed response.
I tried, however, it didn't work unfortunately. 

Inserting a debug code, I found that the DL version has its install directory name PlayClub"DL", so the StartupPath also returns PlayClubDL.

![startup_path](https://cloud.githubusercontent.com/assets/19818419/15964964/18455404-2f56-11e6-8461-37e12c7c07b7.jpg)

Suppose, line 120 should be   "return stringBuilder.ToString();"  instead of  "return Path.GetDirectoryName(stringBuilder.ToString());"  ?

**Comment by Eusth** [comment]
Aaah, yes, you're right. Does it work with the change you proposed?

**Comment by vrvrl0ver** [comment]
Yes. Only changing to "return stringBuider.ToString();", plugins (incl. VRpatch 0.7.2alpha) worked  smoothly.

**Comment by Eusth** [comment]
Thanks a bunch for your assistance! m(_ _)m
