### ISSUE TITLE
PlayClub environment can not work. 

### ISSUE THREAD

**Issue by mayar2** [Eusth/Illusion-Plugins#7]
"Couldn't find awake method. Aborting."
                                                         2016.6.17

PlayClub  == playclub_03_appendmap_0729all.exe

**Comment by mayar2** [comment]
@Eusth 
Creates the Awake method if missing one. (Patch for Secrossphere)  
only for Secrossphere?
Sorry, my English is so bad.  
         Thank you for your great work.

**Comment by mayar2** [comment]
There is an error in the game core file 
https://mega.nz/#!i0gCEJAY!tFwr45ZDkSfk8ppQIx-p5TDnnPvvEqO8TtN8gKpAF5w

**Comment by Eusth** [comment]
Thanks for the bug report! The PR that fixed support for Secrossphere had a bug -- it should work now.

[PlayClub_Patched.zip](https://github.com/Eusth/Illusion-Plugins/files/321110/PlayClub_Patched.zip)

**Comment by mayar2** [comment]
Thank you again. ^o^!
